version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eatsoft_db_container
    restart: always
    environment:
      POSTGRES_USER: quockhanhtruong
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: eatsoft_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: